# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file


version: 2
updates:
  - package-ecosystem: "gitsubmodule"
    directory: "/src/content/vault" # or wherever your submodule is
    schedule:
      interval: "daily"
    # ðŸ‘‡ Add token for authentication
    registries:
      - github-private

registries:
  github-private:
    type: git
    url: git@github.com:BravishkaSkytano/obsidian-vault.git
    ssh-key: "${{secrets.DEPENDABOT_SSH_KEY}}"